name       : python-colorama
version    : 0.3.9
release    : 5
source     :
    - https://github.com/tartley/colorama/archive/0.3.9.tar.gz : 642ea61906cf4c826621fbdc2dfc4ad964b37f795974931b6a2cf8e0bdc41cd5
license    : BSD-3-Clause
component  : programming.python
summary    : Makes ANSI escape character sequences for producing colored terminal
    text
description: |
    Makes ANSI escape character sequences for producing colored terminal text
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
replaces   :
    - python3-colorama
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
