name       : python-colorama
version    : 0.4.3
release    : 6
source     :
    - https://github.com/tartley/colorama/archive/0.4.3.tar.gz : 0d93fc83f70c926cd8437b488ea9c8741f9df2ac2d2d681c40783d5ceef98e2b
homepage   : https://github.com/tartley/colorama
license    : BSD-3-Clause
component  : programming.python
summary    : Makes ANSI escape character sequences for producing colored terminal text
description: |
    Makes ANSI escape character sequences for producing colored terminal text
builddeps  :
    - pkgconfig(python3)
    - python-mock
replaces   :
    - python3-colorama
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
