name       : python-colorama
version    : 0.3.7
release    : 2
source     :
    - https://github.com/tartley/colorama/archive/0.3.7.tar.gz : 23a8999d95b05a26a6ba62015211b3565cb66c6c40f7884825a07fe192ab90bd
license    : BSD-3-Clause
component  : programming.python
summary    : Makes ANSI escape character sequences for producing colored terminal text
description: |
    Makes ANSI escape character sequences for producing colored terminal text
builddeps  :
    - pkgconfig(python-3.5)
replaces   :
    - python3-colorama
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
